name: my-blog_CI/CD

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - develop

jobs:
  # ワークフロー実行時のみエラーになるため一旦コメントアウトとする
  # run_lint-prettier:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     - name: Setup Node.js
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: 'v20.8.0'

  #     - name: Install dependencies
  #       run: | 
  #         npm install
  #         npm ls

  #     - name: Run prettier
  #       run: npm run format

  #     - name: Run lint
  #       run: npm run lint

  run_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'v20.8.0'

      - name: Install dependencies
        run: npm install

      - name: Run test
        run: npm run testAuto


  # build_and_deploy:
  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v2

  #   - name: Install dependencies
  #     run: npm install

  #   - name: Build
  #     run: npm run build

  #   - name: Deploy to server
  #     run: |
  # AWSリソース周りの構築が完了した時に記述予定
  # 例: AWS S3:
  # aws s3 sync build/ s3://your-bucket-name
